sudo: required
dist: xenial
solution: PoC.SharpDiff.sln
jdk: openjdk10
language: csharp
#dotnet: 3.0.100
mono: none

#branches:
#  only:
#    - master
#    - dev

global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
  - ASPNETCORE_ENVIRONMENT=Production
  - ASPNETCORE_DETAILEDERRORS=1

addons:
  sonarcloud:
    organization: jboliveira-github
  snaps:
  - name: dotnet-sdk
    confinement: classic
    channel: latest

before_install:
  - sudo snap alias dotnet-sdk.dotnet dotnet
  - dotnet --version

install:
  - bash ./tools/travis-install-dependencies.sh
  
script:
  - git fetch --unshallow || true
  - bash ./tools/travis-build.sh