language: csharp
solution: PoC.SharpDiff.sln
sudo: required
dist: xenial
dotnet: 2.2
mono: none

branches:
  only:
    - master
    - dev

addons:
  sonarcloud:
    organization: jboliveira-github

before_install:
  - bash ./tools/travis-install-dependencies.sh

script:
  - git fetch --unshallow || true
  - bash ./tools/travis-build.sh
