sudo: required
dist: bionic
solution: PoC.SharpDiff.sln
language: csharp
dotnet: 3.0
mono: none
jdk: openjdk10

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=0
    - ASPNETCORE_ENVIRONMENT=Production
    - ASPNETCORE_DETAILEDERRORS=0

addons:
  sonarcloud:
    organization: jboliveira-github

install:
  - bash ./tools/travis-install-dependencies.sh
  
script:
  - git fetch --unshallow || true
  - bash ./tools/travis-build.sh