# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build -c $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test  -c $(buildConfiguration) ./tests/**/*.Tests.csproj --logger trx --collect "Code coverage"
  displayName: 'dotnet test $(buildConfiguration)'
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: './tests/**/*.trx'