// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PoC.SharpDiff.Persistence.Contexts;

namespace PoC.SharpDiff.Persistence.Migrations
{
    [DbContext(typeof(SharpDiffDbContext))]
    [Migration("20190529114446_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("PoC.SharpDiff.Domain.Models.Content", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("LeftContentData");

                    b.Property<string>("RightContentData");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Id", "LeftContentData");

                    b.HasIndex("Id", "RightContentData");

                    b.ToTable("Content");
                });
#pragma warning restore 612, 618
        }
    }
}
