// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using PoC.SharpDiff.Persistence.Contexts;

namespace PoC.SharpDiff.Persistence.Migrations
{
    [DbContext(typeof(SharpDiffDbContext))]
    [Migration("20190526191841_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PoC.SharpDiff.Domain.Models.Content", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int>("Direction");

                    b.Property<string>("Base64String");

                    b.HasKey("Id", "Direction");

                    b.HasIndex("Id", "Direction");

                    b.ToTable("Content");
                });
#pragma warning restore 612, 618
        }
    }
}
